### ISSUE TITLE
@CuAnnan How to use "*" in Xquery with this API?

### ISSUE THREAD

**Issue by HongHuangNeu** [CuAnnan/php-eXist-db-Client#1]

**Comment by CuAnnan** [comment]
Is there something happening when you try?

**Comment by HongHuangNeu** [comment]
It is fine. I am just getting used to it. Sorry!

**Comment by am2en** [comment]
Not support utf-8 special when search by Arabic language

**Comment by CuAnnan** [comment]
@am2en, Sorry. I had kinda let the project lapse.
I can look into this if you want, but I just threw it together for a specific purpose and made the library open source because it seemed like the thing to do.
